package de.hahn.blog.mavenapp.model.adfbc.facade.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 02 14:04:41 CEST 2020
// ---------------------------------------------------------------------
public interface BMAAppModule extends ApplicationModule {
    String sayHello(String name);
}

